name: Continuous Integration - obsolete
on: [push]
jobs:
  build:
    name: Build and test - obsolete
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo Hello World
