name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build container
      run: docker build --target test --tag todo-app:test .
    - name: run testing
      run: docker run  --name todo-app-test -d -e SECRET_KEY=secret todo-app:test