name: Continuous Integration
on: 
  pull_request:
  push:  
    paths-ignore:
      - '**/README.md'
      
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:    
    - name: Branch output
      run: echo ${{ github.ref }}
    - uses: actions/checkout@v2
    - name: build container
      run: docker build --target test --tag todo-app:test .
    - name: run testing
      run: docker run todo-app:test
  
  Push-to-docker-And-Azure:
    name: Push to DockerHub & Azure
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: iabo77/todoapp:${{ github.sha }}, iabo77/todoapp:latest
        push: true
        target: production
    - name: Push to Azure Webhook
      run: curl -dH -X POST ${{ secrets.AZURE_WEBHOOK_URL }}

   