name: Continuous Integration
on: [push, pull_request]  
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build container
      run: docker build --target test --tag todo-app:test .
    - name: run testing
      run: docker run -e SECRET_KEY=secret todo-app:test