name: Continuous Integration
on: 
  pull_request:
  push:  
    paths-ignore:
      - '**/README.md'
      
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build container
      run: docker build --target test --tag todo-app:test .
    - name: run testing
      run: docker run -e SECRET_KEY=secret todo-app:test
  
  Push-to-Docker:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
    - uses: docker/build-push-action@v3
      with:
        context: .

    