name: Continuous Integration
on: 
  pull_request:
  push:  
    paths-ignore:
      - '**/README.md'

env: 
  username : ${{ secrets.DOCKERHUB_USERNAME }}
      
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build container
      run: docker build --target test --tag todo-app:test .
    - name: run testing
      run: docker run -e SECRET_KEY=secret todo-app:test
  
  Push-to-Docker:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: push to dockerhub
      run:  echo $username
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}